name: Compile and upload

on:
  push:
    tags:
      - '*'

jobs:
  compile_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: surf-surf.tex
      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: surf-surf.pdf
          asset_name: surf-surf.pdf
          tag: ${{ github.ref }}
          overwrite: true
          body: "Paper draft"
